=== shubhamkj5/clientside/XML/store.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT store (mobile)+>
<!ELEMENT mobile (make,model,memory,os,price)>
<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT memory (#PCDATA)>
<!ELEMENT os (name,version)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT version (#PCDATA)>

=== shubhamkj5/clientside/XML/store.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE store SYSTEM "store.dtd">
<store>
	<mobile>
		<make>Samsung</make>
		<model>Note 9</model>
		<memory>128 gb</memory>
		<os>
			<name>Android</name>
			<version>8.1</version>
		</os>
		<price>€700</price>
	</mobile>
	
	<mobile>
		<make>Mi</make>
		<model>Note 5 pro</model>
		<memory>64 gb</memory>
		<os>
			<name>MIUI</name>
			<version>10</version>
		</os>
		<price>€300</price>
	</mobile>
</store>
